### ISSUE TITLE
Use Flexbox for message positioning

### ISSUE THREAD

**Issue by AVGVSTVS96** [AVGVSTVS96/FastGPT#6]
Carryover from [flaskGPT #10](https://github.com/AVGVSTVS96/flaskGPT/issues/10)
Method for positioning messages is probably not ideal, flexbox may be better. Look into this solution or alternatives
```CSS
/* Remove float from .message and use flexbox for .chat-box */
.chat-box {
  display: flex;
  flex-direction: column;
  align-items: flex-end;
  flex-grow: 1;
  width: 100%;
  min-height: 100px;
  margin-bottom: 20px;
  overflow-y: auto;
  padding-right: 10px;
  max-width: calc(100% - 10px);
}

.user-message {
  align-self: flex-end;
}

.assistant-message {
  align-self: flex-start;
}
```
